### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by rkusuma** [SamVerschueren/BB10-MVVMLoginExample#1]
How can i implement dependency injection in this approach? qmlRegisterType can only use default constructor, meanwhile i want to use constructor injection for dependencies in ViewModel class.

Thank you.

**Comment by SamVerschueren** [comment]
You can use setter injection instead of constructor injection. 

First expose the service or whatever you want to inject to QML in applicationui.cpp

``` C++
MyService *service = new MyService(this);

qml->setContextProperty("myService", service);
```

Create a new property in the viewmodel and inject the service via a setter in qml

``` QML
LoginViewModel {
    id: loginVM
    service: myService
}
```

There indeed is no way of doing constructor injection via QML. Hopefully this helps.

**Comment by rkusuma** [comment]
Thanks for the reply Sam..
Do you know Ioc Container and Dependency Injection library for blackberry 10?
I found this QtDependencyResolver (https://github.com/SPupko/QtDependencyResolver) but it not support setter injection.. it's only constructor injection..

Thank You

**Comment by SamVerschueren** [comment]
Actually what you can do is instead of creating your ViewModel in QML, is creating it in C++ and expose it to QML with the setContextProperty. That way you can inject whatever you want in your constructor. 

``` C++
MyService *service = new MyService(this);
LoginViewModel *loginVM = new LoginViewModel(service, this);

qml->setContextProperty("loginVM", loginVM);
```

Then you can probably use the QtDependencyResolver to inject the correct classes. Let me know, sounds cool it it works :).

**Comment by rkusuma** [comment]
If i expose ViewModel with setContextProperty, how can i connect ViewModel signal to the QML slot?
If i creating ViewModel in QML, it's has been done automatically.
Example:
ViewModel class has signal loginComplete();
in QML automatically connecting ViewModel signal to onLoginComplete slot in that QML.

how can i do this if i expose ViewModel using setContextProperty?

**Comment by SamVerschueren** [comment]
It is possible but a little bit more work.

``` QML
Page {
    onCreationCompleted: {
        loginVM.loginComplete.connect(onLoginCompleted);
    }

    function onLoginCompleted() {
        // Do whatever you want when signal is fired
    }
}
```

**Comment by rkusuma** [comment]
Thanks Sam.. 
But when i watch video best practices Blackberry Cascades from BlackBerry Jam (http://hosting.desire2learncapture.com/RIM/1/watch/167.aspx), they state we must avoid using .connect in QML. Is it true?

**Comment by SamVerschueren** [comment]
Ow didn't knew that. Thanks for pointing that out. Will have a deeper look into it later.

**Comment by SamVerschueren** [comment]
Hi @rkusuma, I listened to the video about the .connect() function. This is what they say about it in the video around 28:30.

```
If you have a C++ signal that you want to listen to in QML, you'll have to use it as well.
```

So basically. You shouldn't use it if it's possible to not use it. That is if you can listen for changes in a property of a QML object. In our case, we don't have a QML object, we have a C++ object. So then we don't have a choice. So it's perfectly valid of using the .connect() method.
