### ISSUE TITLE
MVVM vs MVC

### ISSUE THREAD

**Issue by rkusuma** [SamVerschueren/BB10-MVVMLoginExample#2]
Dear Sam,

I just want to know why u using MVVM pattern for blackberry 10? why not MVC?
Can you give me an example using MVC pattern for blackberry 10?

**Comment by SamVerschueren** [comment]
Hi

I came from Windows Phone development and I learned working with MVVM. But I do my latest BlackBerry projects in MVC and I like it. So in my opinion, it's what you prefer.

**Comment by rkusuma** [comment]
Cool..
Can you give me an example for your MVC in BB10?

**Comment by belogermanotta** [comment]
@rkusuma please see BB10 sample
https://developer.blackberry.com/native/sampleapps/

**Comment by rkusuma** [comment]
@emillionchandra there is no useful sampleapps for MVC in BB10.
Can you give an example too?

**Comment by belogermanotta** [comment]
@rkusuma 
https://github.com/blackberry/Cascades-Community-Samples/tree/master/AnnualLeave

This follows directly from the requirement that user interface elements and look and feel should be decoupled from the business logic of the application to allow flexible customisation and re-skinning of the user interface. It also follows good design practice by following the MVC ( Model, View, Controller ) pattern.
