### ISSUE TITLE
Binding

### ISSUE THREAD

**Issue by rkusuma** [SamVerschueren/BB10-MVVMLoginExample#3]
Hey Sams..

I see your beRail application and it is use MVVM too. I want to know why you not using Binding in QML just like in MVVMLoginExample ? what's the differences ?

Thank You

**Comment by SamVerschueren** [comment]
Hi

I changed my coding style during different projects. So now I wouldn't develop beRail the same at how I did it back then. I was no Qt expert at all, so I had to learn a lot myself. No idea why I didn't use the Binding object in QML. Maybe I discovered it after I already had developed beRail... Not quite sure.

**Comment by rkusuma** [comment]
Thank you Sam,

So do you prefer using Binding or do it manually using emit?

**Comment by SamVerschueren** [comment]
I mostly do it using emit. But if you prefer the Binding style, just use it :). What makes you comfortable while coding...
